name: Tests

on:
  push:
    branches: [ assignment-3 ]
  pull_request:
    branches: [ assignment-3 ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock requests

    - name: Add project to PYTHONPATH
      run: echo "PYTHONPATH=." >> $GITHUB_ENV
    
    - name: Install Python Playwright.
      run: |
          playwright install --with-deps

    - name: Begin Flask app. 
      run: |
        nohup python app.py &
        sleep 3

    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=services --cov-report=xml
    
    - name: Upload coverage to Codecov

      uses: codecov/codecov-action@v3

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}








